require 'rubygems'
require 'bundler/setup'
begin
  require 'dotenv'
  Dotenv.load
rescue LoadError
end
begin
  require 'rspec/core/rake_task'

  namespace :spec do
    RSpec::Core::RakeTask.new(:unit_tests) do |task|
      task.rspec_opts = ["-c", "-f progress", "-r ./spec/spec_helper.rb"]
      task.pattern    = 'spec/unit_tests/**/*_spec.rb'
    end
    RSpec::Core::RakeTask.new(:acceptance) do |task|
      task.rspec_opts = ["-c", "-f documentation", "-r ./spec/acceptance_helper.rb"]
      task.pattern    = 'spec/acceptance/**/*_feature.rb'
    end
  end
rescue LoadError
  # RSpec is not available, skipping spec tasks
end

namespace :db do
  require "sequel"
  Sequel.extension :migration
  DB = Sequel.connect(ENV['DATABASE_URL'])

  desc "Prints current schema version"
  task :version do
    version = if DB.tables.include?(:schema_info)
      DB[:schema_info].first[:version]
    end || 0

    puts "Schema Version: #{version}"
  end

  desc "Perform migration up to latest migration available"
  task :migrate do
    Sequel::Migrator.run(DB, "migrations")
    Rake::Task['db:version'].execute
  end

  desc "Perform rollback to specified target or full rollback as default"
  task :rollback, :target do |t, args|
    args.with_defaults(:target => 0)

    Sequel::Migrator.run(DB, "migrations", :target => args[:target].to_i)
    Rake::Task['db:version'].execute
  end

  desc "Perform migration reset (full rollback and migration)"
  task :reset do
    Sequel::Migrator.run(DB, "migrations", :target => 0)
    Sequel::Migrator.run(DB, "migrations")
    Rake::Task['db:version'].execute
  end

  desc "Load seed data into the database"
  task :seed do
    puts "Loading ceds.sql into database..."
    `psql #{ENV['DATABASE_URL']} < ceds.sql`
    puts "Done."
  end
end
